
- name: Import grafana gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.grafana.com/gpg.key

- name: Install grafana
  yum:
    name: https://dl.grafana.com/oss/release/grafana-{{ version }}-1.x86_64.rpm
    state: latest

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200
